# Generated by Django 3.2.16 on 2023-01-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(blank=True, choices=[('RUS', 'Россия'), ('UZB', 'Узбекистан')], db_index=True, default='UZB', max_length=255, verbose_name='Город'),
        ),
    ]
