# Generated by Django 3.2.16 on 2022-12-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ice_cream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', help_text='Клубничка', max_length=100, verbose_name='name')),
                ('sort_of', models.CharField(db_index=True, default='', help_text='Пломбир', max_length=100, verbose_name='sort_of')),
                ('price', models.FloatField(db_index=True, default='', max_length=100, verbose_name='price')),
            ],
            options={
                'verbose_name': 'Мороженое',
                'verbose_name_plural': 'Мороженое',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Ice_cream_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_create', models.DateField(db_index=True, default='', help_text='2022-01-01', max_length=100, verbose_name='Date')),
                ('address', models.CharField(db_index=True, default='', help_text='ул. Ленина, 12', max_length=100, verbose_name='age')),
                ('name', models.CharField(db_index=True, default='', help_text='Чебурашка', max_length=100, verbose_name='age')),
                ('ower', models.CharField(db_index=True, default='', help_text='Белый Хозяин', max_length=100, verbose_name='age')),
                ('geo', models.CharField(db_index=True, default='', help_text='48.1212121, 68.565656', max_length=100, verbose_name='age')),
            ],
            options={
                'verbose_name': 'Киоск',
                'verbose_name_plural': 'Киоски',
                'ordering': ['-pk'],
            },
        ),
    ]
