# Generated by Django 3.2.16 on 2023-01-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0002_alter_city_city'),
        ('icecream_app', '0004_alter_ice_cream_shop_date_of_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='ice_cream_shop',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_app.city'),
            preserve_default=False,
        ),
    ]
