# Generated by Django 3.2.16 on 2022-12-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(db_index=True, default='', help_text='Иван Иванович Иванов', max_length=100, verbose_name='fio')),
                ('age', models.IntegerField(db_index=True, default='', help_text='18', verbose_name='age')),
                ('birth_date', models.DateField(db_index=True, default='', verbose_name='birth_date')),
                ('gender', models.BooleanField(db_index=True, default='', verbose_name='gender')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Humans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(db_index=True, default='', help_text='Иван Иванович Иванов', max_length=100, verbose_name='fio')),
                ('age', models.IntegerField(db_index=True, default='', help_text='18', verbose_name='age')),
                ('birth_date', models.DateField(db_index=True, default='', verbose_name='birth_date')),
                ('gender', models.BooleanField(db_index=True, default='', verbose_name='gender')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['-pk'],
            },
        ),
    ]
