# Generated by Django 3.2.16 on 2022-12-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans_app', '0003_alter_humans_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humans',
            name='age',
            field=models.IntegerField(db_index=True, default='', help_text='18', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='humans',
            name='fio',
            field=models.CharField(db_index=True, default='', help_text='Иван Иванович Иванов', max_length=100, verbose_name='ФИО'),
        ),
    ]
