# Generated by Django 3.2.16 on 2022-12-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans_app', '0004_auto_20221226_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humans',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(1, 'Male'), (0, 'Female')], db_index=True, default=None, verbose_name='gender'),
        ),
    ]
