# Generated by Django 3.2.16 on 2022-12-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans_app', '0005_alter_humans_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humans',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(None, 'Не определенно'), (1, 'Мужчина'), (0, 'Женщина')], db_index=True, default=None, verbose_name='gender'),
        ),
    ]
