# Generated by Django 3.2.16 on 2022-12-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans_app', '0007_humans_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humans',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='humans_app.child'),
        ),
    ]
