# Generated by Django 3.2.16 on 2022-12-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans_app', '0008_alter_humans_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRelationShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Отнашения',
                'verbose_name_plural': 'Отнашения',
            },
        ),
        migrations.AlterModelOptions(
            name='child',
            options={},
        ),
        migrations.AlterModelOptions(
            name='humans',
            options={'get_latest_by': ['-age'], 'ordering': ['-pk'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.RemoveField(
            model_name='child',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='child',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='humans',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='humans',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='humans',
            name='parent',
        ),
        migrations.AddField(
            model_name='child',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='child',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='humans',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='humans',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='humans',
            name='name_terms',
            field=models.CharField(choices=[('Blasic', (('mr', 'Mr'), ('ms', 'Ms'))), ('Prof', (('dr', 'Dr'), ('sir', 'Sir'))), ('unknown', 'Unknown')], default=(('dr', 'Dr'), ('sir', 'Sir')), max_length=255, verbose_name='Обращение'),
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Вщзраст'),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(None, 'Не определенно'), (1, 'Мужчина'), (0, 'Женщина')], default=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='humans',
            name='age',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Вазраст'),
        ),
        migrations.AlterField(
            model_name='humans',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(None, 'Не определенно'), (1, 'Мужчина'), (0, 'Женщина')], default=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddConstraint(
            model_name='humans',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 16)), name='age'),
        ),
        migrations.AddField(
            model_name='personrelationship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humans_app.child'),
        ),
        migrations.AddField(
            model_name='personrelationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humans_app.humans'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent_field',
            field=models.ManyToManyField(through='humans_app.PersonRelationShip', to='humans_app.Humans'),
        ),
        migrations.AlterUniqueTogether(
            name='personrelationship',
            unique_together={('child',)},
        ),
    ]
