# Generated by Django 3.2.16 on 2023-01-09 14:28

import django.core.validators
from django.db import migrations, models
import humans_app.validators
import re


class Migration(migrations.Migration):

    dependencies = [
        ('humans_app', '0009_auto_20221229_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[humans_app.validators.validate_address_lenght], verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Введите строку', regex='^\\D+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='humans',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[humans_app.validators.validate_address_lenght], verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='humans',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Введите строку', regex='^\\D+$')], verbose_name='Имя'),
        ),
    ]
